// Offline heuristic grader for local UI testing when no ANTHROPIC_API_KEY is available (GRADER=mock).
// It only understands the shipped template's criterion ids and is NOT used in production.

const SENSITIVE_ACTION = /password|reset link|2fa|two-factor|annual plan|refund the difference/;
const VERIFIED = /last (4|four)|zip code|invoice amount/;

function snippet(text, regex) {
  const match = text.match(regex);
  if (!match) return text.slice(0, 140);
  const start = Math.max(0, match.index - 40);
  return text.slice(start, start + 140).trim();
}

const RULES = {
  acknowledge(agent) {
    if (/sorry|understand|frustrat|i can imagine|stressful|scary|disappointing|i can hear|totally fair/.test(agent)) return ['yes', /sorry|understand|frustrat|imagine|stressful|scary|disappointing|hear|fair/];
    if (/apolog/.test(agent)) return ['partial', /apolog/];
    return ['no', null];
  },
  tone(agent) {
    if (/are you sure|regret|you'll lose|call back/.test(agent)) return ['no', /are you sure|regret|lose|call back/];
    return agent.length < 140 ? ['partial', null] : ['yes', null];
  },
  understanding(agent) {
    return agent.length < 60 ? ['partial', null] : ['yes', null];
  },
  resolved(agent) {
    const acted = /refund|reversed|sent|reset|disabled|scheduled|process|export|turned|switched|credit|downgrade|off now/;
    if (acted.test(agent) && agent.length > 200) return ['yes', acted];
    return acted.test(agent) ? ['partial', acted] : ['no', null];
  },
  next_steps(agent) {
    const concrete = /\d+\s*(-|to)\s*\d+\s*(business )?days|tomorrow|within \d+|by (friday|thursday)|minutes|24 hours/;
    if (concrete.test(agent)) return ['yes', concrete];
    if (/soon|eventually|few days|week or so|when there's movement/.test(agent)) return ['partial', /soon|eventually|few days|week or so|movement/];
    return ['no', null];
  },
  clarity(agent) {
    if (agent.length > 200) return ['yes', null];
    return agent.length > 90 ? ['partial', null] : ['no', null];
  },
  identity_verification(agent, all) {
    if (!SENSITIVE_ACTION.test(all)) return ['na', null];
    return VERIFIED.test(agent) ? ['pass', VERIFIED] : ['fail', /what's the (account )?email|account email|email on the account/];
  },
  sensitive_data(agent) {
    return /temp\d+|reset it to \w+/.test(agent) ? ['fail', /temp\d+|reset it to \w+/] : ['pass', null];
  },
  proactive(agent) {
    const extra = /recommend|credit|personally|i'll (check|follow|stay|chase)|flagged|backup codes|guide|stay online/;
    return extra.test(agent) ? ['yes', extra] : ['no', null];
  },
};

function grade(scorecard, transcript) {
  const agent = transcript.turns
    .filter((t) => t.speaker === 'agent')
    .map((t) => t.body)
    .join(' ')
    .toLowerCase();
  const all = transcript.turns.map((t) => t.body).join(' ').toLowerCase();

  const answers = scorecard.sections.flatMap((section) =>
    section.criteria.map((criterion) => {
      const rule = RULES[criterion.id];
      if (!rule) {
        return { criterion_id: criterion.id, option_id: criterion.options[0].id, evidence: 'Mock grader has no rule for this criterion.', confidence: 'low' };
      }
      const [optionId, regex] = rule(agent, all);
      return {
        criterion_id: criterion.id,
        option_id: optionId,
        evidence: optionId === 'na' ? 'No sensitive account action in this ticket.' : snippet(agent, regex || /./),
        confidence: 'medium',
      };
    })
  );

  return { answers, summary: 'Graded by the offline mock grader (GRADER=mock).', usage: null, model: 'mock' };
}

function draftCoaching(agentName, weakCriteria) {
  return {
    summary: `${agentName} has ${weakCriteria.length} areas to focus on. Suggestions below are generated by the offline mock grader.`,
    points: weakCriteria.map((c) => ({
      criterion_id: c.criterion_id,
      observation: `Averaging ${c.average_pct}% on "${c.question}".`,
      suggestion: 'Review the example ticket together and rewrite the reply using the scorecard guidance.',
      example_ticket_id: c.examples[0] ? c.examples[0].ticket_id : '',
    })),
    usage: null,
    model: 'mock',
  };
}

module.exports = { grade, draftCoaching };
